version: '3'

services:
  app:
    build: .
    container_name: app
    tty: true
    networks:
      - app-network
  redis:
    image: redis:alpine
    container_name: redis
    tty: true
    networks:
      - app-network
networks:
  app-network:
    driver: bridge